- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/hyper.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/personal-projects.yml
