- name: Git - Setup email
  git_config:
    name: user.email
    scope: global
    value: "hi@fabioromeiro.dev"
  tags:
    - git
    - config

- name: Git - Setup name
  git_config: 
    name: user.name
    scope: global
    value: "FabioRomeiro"
  tags:
    - git
    - config

